-- ── KOSPI 대형주 / 중형주 ──────────────────────────────────────────────────
INSERT INTO stocks (symbol, name, market, exchange, sector, industry, country, currency, is_active) VALUES
-- 시가총액 상위 (삼성·SK·현대·LG 그룹 포함)
('005930','삼성전자','KOSPI','KRX','전기전자','반도체·디스플레이','KR','KRW',true),
('000660','SK하이닉스','KOSPI','KRX','전기전자','반도체','KR','KRW',true),
('005380','현대차','KOSPI','KRX','운수장비','자동차','KR','KRW',true),
('035420','NAVER','KOSPI','KRX','서비스업','인터넷 플랫폼','KR','KRW',true),
('005490','POSCO홀딩스','KOSPI','KRX','철강금속','철강','KR','KRW',true),
('000270','기아','KOSPI','KRX','운수장비','자동차','KR','KRW',true),
('068270','셀트리온','KOSPI','KRX','의약품','바이오의약품','KR','KRW',true),
('105560','KB금융','KOSPI','KRX','금융업','은행','KR','KRW',true),
('055550','신한지주','KOSPI','KRX','금융업','은행','KR','KRW',true),
('012330','현대모비스','KOSPI','KRX','운수장비','자동차부품','KR','KRW',true),
('003550','LG','KOSPI','KRX','기타','지주회사','KR','KRW',true),
('051910','LG화학','KOSPI','KRX','화학','석유화학','KR','KRW',true),
('035720','카카오','KOSPI','KRX','서비스업','인터넷 플랫폼','KR','KRW',true),
('066570','LG전자','KOSPI','KRX','전기전자','가전·디스플레이','KR','KRW',true),
('096770','SK이노베이션','KOSPI','KRX','화학','정유·배터리','KR','KRW',true),
('034730','SK','KOSPI','KRX','기타','지주회사','KR','KRW',true),
('028260','삼성물산','KOSPI','KRX','건설업','건설','KR','KRW',true),
('086790','하나금융지주','KOSPI','KRX','금융업','은행','KR','KRW',true),
('015760','한국전력','KOSPI','KRX','전기가스','전력','KR','KRW',true),
('030200','KT','KOSPI','KRX','통신업','통신','KR','KRW',true),
('017670','SK텔레콤','KOSPI','KRX','통신업','통신','KR','KRW',true),
('032830','삼성생명','KOSPI','KRX','금융업','보험','KR','KRW',true),
('018260','삼성에스디에스','KOSPI','KRX','서비스업','IT서비스','KR','KRW',true),
('009150','삼성전기','KOSPI','KRX','전기전자','전자부품','KR','KRW',true),
('010950','S-Oil','KOSPI','KRX','화학','정유','KR','KRW',true),
('011170','롯데케미칼','KOSPI','KRX','화학','석유화학','KR','KRW',true),
('000810','삼성화재','KOSPI','KRX','금융업','보험','KR','KRW',true),
('006400','삼성SDI','KOSPI','KRX','전기전자','배터리','KR','KRW',true),
('034020','두산에너빌리티','KOSPI','KRX','기계','발전설비','KR','KRW',true),
('316140','우리금융지주','KOSPI','KRX','금융업','은행','KR','KRW',true),
('003490','대한항공','KOSPI','KRX','운수창고','항공','KR','KRW',true),
('011200','HMM','KOSPI','KRX','운수창고','해운','KR','KRW',true),
('078930','GS','KOSPI','KRX','기타','지주회사','KR','KRW',true),
('036460','한국가스공사','KOSPI','KRX','전기가스','가스','KR','KRW',true),
('033780','KT&G','KOSPI','KRX','음식료','담배','KR','KRW',true),
('004020','현대제철','KOSPI','KRX','철강금속','철강','KR','KRW',true),
('071050','한국금융지주','KOSPI','KRX','금융업','증권','KR','KRW',true),
('024110','기업은행','KOSPI','KRX','금융업','은행','KR','KRW',true),
('047810','한국항공우주','KOSPI','KRX','운수장비','항공우주','KR','KRW',true),
('090430','아모레퍼시픽','KOSPI','KRX','화학','화장품','KR','KRW',true),
('000100','유한양행','KOSPI','KRX','의약품','제약','KR','KRW',true),
('097950','CJ제일제당','KOSPI','KRX','음식료','식품','KR','KRW',true),
('021240','코웨이','KOSPI','KRX','전기전자','생활가전','KR','KRW',true),
('002790','아모레G','KOSPI','KRX','화학','화장품','KR','KRW',true),
('000720','현대건설','KOSPI','KRX','건설업','건설','KR','KRW',true),
('161390','한국타이어앤테크놀로지','KOSPI','KRX','운수장비','타이어','KR','KRW',true),
('010130','고려아연','KOSPI','KRX','철강금속','비철금속','KR','KRW',true),
('007070','GS리테일','KOSPI','KRX','유통업','편의점','KR','KRW',true),
('001040','CJ','KOSPI','KRX','기타','지주회사','KR','KRW',true),
('036570','엔씨소프트','KOSPI','KRX','서비스업','게임','KR','KRW',true),
('251270','넷마블','KOSPI','KRX','서비스업','게임','KR','KRW',true),
('112040','위메이드','KOSPI','KRX','서비스업','게임','KR','KRW',true),
('067160','어비스코퍼레이션','KOSPI','KRX','서비스업','게임','KR','KRW',true),
('030000','제일기획','KOSPI','KRX','서비스업','광고','KR','KRW',true),
('180640','한진칼','KOSPI','KRX','기타','지주회사','KR','KRW',true),
('008770','호텔신라','KOSPI','KRX','서비스업','호텔·면세','KR','KRW',true),
('011780','금호석유','KOSPI','KRX','화학','합성고무','KR','KRW',true),
('009240','한샘','KOSPI','KRX','기타','가구·인테리어','KR','KRW',true),
('006360','GS건설','KOSPI','KRX','건설업','건설','KR','KRW',true),
('000880','한화','KOSPI','KRX','기타','지주회사','KR','KRW',true),
('012450','한화에어로스페이스','KOSPI','KRX','기계','방산·항공','KR','KRW',true),
('267250','현대중공업지주','KOSPI','KRX','기계','조선·지주','KR','KRW',true),
('009830','한화솔루션','KOSPI','KRX','화학','태양광·화학','KR','KRW',true),
('042660','한화오션','KOSPI','KRX','기계','조선','KR','KRW',true),
('329180','현대중공업','KOSPI','KRX','기계','조선','KR','KRW',true),
('010140','삼성중공업','KOSPI','KRX','기계','조선','KR','KRW',true),
('000150','두산','KOSPI','KRX','기타','지주회사','KR','KRW',true),
('005940','NH투자증권','KOSPI','KRX','금융업','증권','KR','KRW',true),
('016360','삼성증권','KOSPI','KRX','금융업','증권','KR','KRW',true),
('003600','SK케미칼','KOSPI','KRX','화학','제약·화학','KR','KRW',true),
('000080','하이트진로','KOSPI','KRX','음식료','주류','KR','KRW',true),
('007310','오뚜기','KOSPI','KRX','음식료','식품','KR','KRW',true),
('005180','빙그레','KOSPI','KRX','음식료','식품','KR','KRW',true),
('271560','오리온','KOSPI','KRX','음식료','식품','KR','KRW',true),
('004370','농심','KOSPI','KRX','음식료','식품','KR','KRW',true),
('005300','롯데칠성','KOSPI','KRX','음식료','음료','KR','KRW',true),
('004000','롯데정밀화학','KOSPI','KRX','화학','정밀화학','KR','KRW',true),
('023530','롯데쇼핑','KOSPI','KRX','유통업','백화점','KR','KRW',true),
('069960','현대백화점','KOSPI','KRX','유통업','백화점','KR','KRW',true),
('139480','이마트','KOSPI','KRX','유통업','대형마트','KR','KRW',true),
('006110','삼아알미늄','KOSPI','KRX','철강금속','알루미늄','KR','KRW',true),
('011790','SKC','KOSPI','KRX','화학','화학·소재','KR','KRW',true),
('008560','메리츠화재','KOSPI','KRX','금융업','보험','KR','KRW',true),
('138040','메리츠금융지주','KOSPI','KRX','금융업','금융지주','KR','KRW',true),
('000040','KYK','KOSPI','KRX','전기전자','정수기','KR','KRW',true),
('002380','KCC','KOSPI','KRX','화학','도료·건자재','KR','KRW',true),
('014820','동원시스템즈','KOSPI','KRX','제조업','포장재','KR','KRW',true),
('007860','서연이화','KOSPI','KRX','운수장비','자동차부품','KR','KRW',true),
('005810','풍산','KOSPI','KRX','철강금속','비철금속','KR','KRW',true),
('001430','세아베스틸지주','KOSPI','KRX','철강금속','철강','KR','KRW',true),
('100840','SNT모티브','KOSPI','KRX','운수장비','방산·자동차','KR','KRW',true),
('192400','쿠쿠홀딩스','KOSPI','KRX','전기전자','생활가전','KR','KRW',true),
('003410','쌍용C&E','KOSPI','KRX','건설업','시멘트','KR','KRW',true),
('000210','대림산업','KOSPI','KRX','건설업','건설','KR','KRW',true),
('047040','대우건설','KOSPI','KRX','건설업','건설','KR','KRW',true),
('006800','미래에셋증권','KOSPI','KRX','금융업','증권','KR','KRW',true),
('039490','키움증권','KOSPI','KRX','금융업','증권','KR','KRW',true),
('001800','오리온홀딩스','KOSPI','KRX','기타','지주회사','KR','KRW',true),
('004490','세방전지','KOSPI','KRX','전기전자','배터리','KR','KRW',true),
('018880','한온시스템','KOSPI','KRX','운수장비','자동차부품','KR','KRW',true),

-- ── KOSDAQ 대형주 / 주요 테마주 ──────────────────────────────────────────
('247540','에코프로비엠','KOSDAQ','KRX','전기전자','배터리소재','KR','KRW',true),
('086520','에코프로','KOSDAQ','KRX','전기전자','배터리소재','KR','KRW',true),
('373220','LG에너지솔루션','KOSPI','KRX','전기전자','배터리','KR','KRW',true),
('096530','씨젠','KOSDAQ','KRX','의약품','체외진단','KR','KRW',true),
('145020','휴젤','KOSDAQ','KRX','의약품','바이오','KR','KRW',true),
('263750','펄어비스','KOSDAQ','KRX','서비스업','게임','KR','KRW',true),
('112610','씨에스윈드','KOSDAQ','KRX','기계','풍력','KR','KRW',true),
('041510','에스엠','KOSDAQ','KRX','서비스업','엔터테인먼트','KR','KRW',true),
('035900','JYP Ent.','KOSDAQ','KRX','서비스업','엔터테인먼트','KR','KRW',true),
('122870','와이지엔터테인먼트','KOSDAQ','KRX','서비스업','엔터테인먼트','KR','KRW',true),
('293490','카카오게임즈','KOSDAQ','KRX','서비스업','게임','KR','KRW',true),
('259960','크래프톤','KOSPI','KRX','서비스업','게임','KR','KRW',true),
('078340','컴투스','KOSDAQ','KRX','서비스업','게임','KR','KRW',true),
('225570','넥슨게임즈','KOSDAQ','KRX','서비스업','게임','KR','KRW',true),
('095660','네오위즈','KOSDAQ','KRX','서비스업','게임','KR','KRW',true),
('181710','NHN','KOSDAQ','KRX','서비스업','IT','KR','KRW',true),
('035080','인터파크트리플','KOSDAQ','KRX','서비스업','여행·커머스','KR','KRW',true),
('053800','안랩','KOSDAQ','KRX','서비스업','보안','KR','KRW',true),
('357780','솔브레인','KOSDAQ','KRX','화학','반도체소재','KR','KRW',true),
('336370','솔브레인홀딩스','KOSDAQ','KRX','기타','지주회사','KR','KRW',true),
('036830','솔브레인이엔에스','KOSDAQ','KRX','화학','화학','KR','KRW',true),
('091990','셀트리온헬스케어','KOSDAQ','KRX','의약품','바이오','KR','KRW',true),
('196170','알테오젠','KOSDAQ','KRX','의약품','바이오','KR','KRW',true),
('141080','리가켐바이오','KOSDAQ','KRX','의약품','바이오','KR','KRW',true),
('214450','파마리서치','KOSDAQ','KRX','의약품','바이오','KR','KRW',true),
('328130','루닛','KOSDAQ','KRX','서비스업','AI·의료','KR','KRW',true),
('236340','스튜디오드래곤','KOSDAQ','KRX','서비스업','콘텐츠','KR','KRW',true),
('950130','엑스페릭스','KOSDAQ','KRX','전기전자','반도체','KR','KRW',true),
('039030','이오테크닉스','KOSDAQ','KRX','기계','반도체장비','KR','KRW',true),
('048260','오스템임플란트','KOSDAQ','KRX','의료기기','치과','KR','KRW',true),
('900290','GH신소재','KOSDAQ','KRX','화학','소재','KR','KRW',true),
('054620','APS홀딩스','KOSDAQ','KRX','전기전자','반도체장비','KR','KRW',true),
('036810','에프에스티','KOSDAQ','KRX','전기전자','반도체장비','KR','KRW',true),
('108320','LX세미콘','KOSDAQ','KRX','전기전자','반도체','KR','KRW',true),
('089030','테크윙','KOSDAQ','KRX','기계','반도체장비','KR','KRW',true),
('079940','가비아','KOSDAQ','KRX','서비스업','IT인프라','KR','KRW',true),
('041920','메디아나','KOSDAQ','KRX','의료기기','의료','KR','KRW',true),
('206640','바디텍메드','KOSDAQ','KRX','의료기기','체외진단','KR','KRW',true),
('950140','잉글우드랩','KOSDAQ','KRX','화학','화장품','KR','KRW',true),
('060250','NHN한국사이버결제','KOSDAQ','KRX','서비스업','핀테크','KR','KRW',true),
('131970','두산테스나','KOSDAQ','KRX','전기전자','반도체','KR','KRW',true),
('064290','인텍플러스','KOSDAQ','KRX','기계','검사장비','KR','KRW',true),
('049830','에스아이에스','KOSDAQ','KRX','전기전자','디스플레이','KR','KRW',true),
('183300','코미코','KOSDAQ','KRX','전기전자','반도체부품','KR','KRW',true),
('054450','텔레칩스','KOSDAQ','KRX','전기전자','반도체','KR','KRW',true),
('030190','NICE평가정보','KOSDAQ','KRX','서비스업','데이터','KR','KRW',true),
('060280','큐렉소','KOSDAQ','KRX','의료기기','수술로봇','KR','KRW',true),
('348210','넥스틴','KOSDAQ','KRX','기계','반도체장비','KR','KRW',true),
('054950','에이텍','KOSDAQ','KRX','전기전자','IT기기','KR','KRW',true),
('900070','에이치엔에이탐색','KOSDAQ','KRX','서비스업','AI','KR','KRW',true),

-- ── 미국 주요 종목 (NASDAQ / NYSE) ────────────────────────────────────────
('AAPL','Apple','NASDAQ','NASDAQ','전기전자','스마트폰·PC','US','USD',true),
('MSFT','Microsoft','NASDAQ','NASDAQ','서비스업','클라우드·OS','US','USD',true),
('NVDA','NVIDIA','NASDAQ','NASDAQ','전기전자','GPU·AI반도체','US','USD',true),
('GOOGL','Alphabet (Google)','NASDAQ','NASDAQ','서비스업','인터넷·광고','US','USD',true),
('META','Meta Platforms','NASDAQ','NASDAQ','서비스업','소셜미디어','US','USD',true),
('AMZN','Amazon','NASDAQ','NASDAQ','유통업','이커머스·클라우드','US','USD',true),
('TSLA','Tesla','NASDAQ','NASDAQ','운수장비','전기차','US','USD',true),
('AVGO','Broadcom','NASDAQ','NASDAQ','전기전자','반도체','US','USD',true),
('TSM','TSMC','NYSE','NYSE','전기전자','반도체파운드리','TW','USD',true),
('AMD','AMD','NASDAQ','NASDAQ','전기전자','CPU·GPU','US','USD',true),
('INTC','Intel','NASDAQ','NASDAQ','전기전자','CPU·반도체','US','USD',true),
('QCOM','Qualcomm','NASDAQ','NASDAQ','전기전자','모바일 반도체','US','USD',true),
('NFLX','Netflix','NASDAQ','NASDAQ','서비스업','스트리밍','US','USD',true),
('SPOT','Spotify','NYSE','NYSE','서비스업','음악 스트리밍','SE','USD',true),
('CRM','Salesforce','NYSE','NYSE','서비스업','SaaS·CRM','US','USD',true),
('ORCL','Oracle','NYSE','NYSE','서비스업','DB·클라우드','US','USD',true),
('IBM','IBM','NYSE','NYSE','서비스업','IT서비스·AI','US','USD',true),
('JPM','JPMorgan Chase','NYSE','NYSE','금융업','은행','US','USD',true),
('BAC','Bank of America','NYSE','NYSE','금융업','은행','US','USD',true),
('GS','Goldman Sachs','NYSE','NYSE','금융업','투자은행','US','USD',true),
('V','Visa','NYSE','NYSE','금융업','결제','US','USD',true),
('MA','Mastercard','NYSE','NYSE','금융업','결제','US','USD',true),
('PYPL','PayPal','NASDAQ','NASDAQ','금융업','핀테크','US','USD',true),
('JNJ','Johnson & Johnson','NYSE','NYSE','의약품','제약·의료기기','US','USD',true),
('PFE','Pfizer','NYSE','NYSE','의약품','제약','US','USD',true),
('MRNA','Moderna','NASDAQ','NASDAQ','의약품','mRNA 백신','US','USD',true),
('UNH','UnitedHealth','NYSE','NYSE','의약품','의료보험','US','USD',true),
('XOM','ExxonMobil','NYSE','NYSE','화학','정유','US','USD',true),
('CVX','Chevron','NYSE','NYSE','화학','정유','US','USD',true),
('BA','Boeing','NYSE','NYSE','운수장비','항공기','US','USD',true),
('CAT','Caterpillar','NYSE','NYSE','기계','건설기계','US','USD',true),
('DIS','Disney','NYSE','NYSE','서비스업','미디어·테마파크','US','USD',true),
('SBUX','Starbucks','NASDAQ','NASDAQ','음식료','커피','US','USD',true),
('NKE','Nike','NYSE','NYSE','기타','스포츠용품','US','USD',true),
('MCD','McDonald''s','NYSE','NYSE','음식료','외식','US','USD',true),
('COIN','Coinbase','NASDAQ','NASDAQ','금융업','암호화폐거래소','US','USD',true),
('PLTR','Palantir','NYSE','NYSE','서비스업','AI·데이터분석','US','USD',true),
('SNOW','Snowflake','NYSE','NYSE','서비스업','클라우드 데이터','US','USD',true),
('UBER','Uber','NYSE','NYSE','서비스업','모빌리티','US','USD',true),
('LYFT','Lyft','NASDAQ','NASDAQ','서비스업','모빌리티','US','USD',true),
('ABNB','Airbnb','NASDAQ','NASDAQ','서비스업','숙박플랫폼','US','USD',true),
('SHOP','Shopify','NYSE','NYSE','서비스업','이커머스 SaaS','CA','USD',true),
('SQ','Block (Square)','NYSE','NYSE','금융업','핀테크','US','USD',true),
('HOOD','Robinhood','NASDAQ','NASDAQ','금융업','리테일 증권','US','USD',true),
('ARM','Arm Holdings','NASDAQ','NASDAQ','전기전자','반도체설계','GB','USD',true),
('SMCI','Super Micro Computer','NASDAQ','NASDAQ','전기전자','서버','US','USD',true),
('DELL','Dell Technologies','NYSE','NYSE','전기전자','PC·서버','US','USD',true),
('HPQ','HP Inc.','NYSE','NYSE','전기전자','PC·프린터','US','USD',true),
('PANW','Palo Alto Networks','NASDAQ','NASDAQ','서비스업','사이버보안','US','USD',true),
('CRWD','CrowdStrike','NASDAQ','NASDAQ','서비스업','사이버보안','US','USD',true),
('ZS','Zscaler','NASDAQ','NASDAQ','서비스업','사이버보안','US','USD',true)
ON CONFLICT (symbol, market) DO NOTHING;
