name: Feature
description: monticker feature task
title: "[Feature] "
labels: ["feature"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What should be built?
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: Affected apps/modules
      placeholder: |
        - backend/api
        - apps/web
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
    validations:
      required: true
  - type: textarea
    id: constraints
    attributes:
      label: Constraints
  - type: textarea
    id: test
    attributes:
      label: Test Plan
