apiVersion: v1
kind: ConfigMap
metadata:
  name: monticker-config
  namespace: monticker
data:
  DB_URL: "jdbc:postgresql://postgres:5432/monticker"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  KAFKA_BROKERS: "kafka:9092"
  INGESTION_SOURCE: "internal"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4318"
  PINPOINT_ENABLE: "false"
  PINPOINT_COLLECTOR_IP: "pinpoint-collector"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: market-gateway-config
  namespace: monticker
data:
  KAFKA_BROKERS: "kafka:9092"
  DB_URL: "postgres://monticker:monticker@postgres:5432/monticker?sslmode=disable"
