apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monticker

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - api.yaml
  - worker.yaml
  - web.yaml
  - market-gateway.yaml
  - quant-engine.yaml
  - trading-service.yaml
  - worker-market.yaml
  - worker-event.yaml
  - worker-alert.yaml
  - jaeger.yaml
  - ingress.yaml
