apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # prod: HPA 최소 replica를 3으로 상향
  - patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 3
    target:
      kind: HorizontalPodAutoscaler
      name: api-hpa

images:
  - name: monticker/api
    newTag: "1.0.0"
  - name: monticker/worker
    newTag: "1.0.0"
  - name: monticker/web
    newTag: "1.0.0"
  - name: monticker/market-gateway
    newTag: "1.0.0"
